### ISSUE TITLE
How to add a label in each item in the chart pie?

### ISSUE THREAD

**Issue by MarialenaShiamma** [marshallino16/PacPieChart-Android#1]
I added and run successfully the example of yours in my application and I just want to add a label in each item of the chart pie. I changed your command related with the label, because I couldn't find what "answer" was. My current command is this: " item3.label = "Here"; " but I can't see it anywhere near the item3 part of the chart pie.

**Comment by marshallino16** [comment]
There's no label yet but next update will bring this feature.
